# Bind role to service account : connect triton-sa to triton-role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: triton-rolebinding
  namespace: triton
subjects:
  - kind: ServiceAccount
    name: triton-sa
    namespace: triton
roleRef:
  kind: Role
  name: triton-role
  apiGroup: rbac.authorization.k8s.io
