#Provides HTTP (8000), gRPC (8001), metrics (8002).

apiVersion: v1
kind: Service
metadata:
  name: {{ include "triton.fullname" . }}
  labels:
    app: {{ include "triton.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      name: http
    - port: {{ .Values.service.grpc_port }}
      targetPort: grpc
      name: grpc
    - port: {{ .Values.service.metrics_port }}
      targetPort: metrics
      name: metrics
  selector:
    app: {{ include "triton.name" . }}
