---
name: Build & Push Triton Image

on:
  push:
    branches: ["main"]
    paths:
      - "services/triton/**"

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production    # optional but recommended

    steps:
      - uses: actions/checkout@v4

      - name: Debug AWS role
        run: echo "Using AWS_OIDC_ROLE_ARN secret"

      - name: Debug GitHub context
        run: |
            echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
            echo "GITHUB_REF=$GITHUB_REF"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          audience: sts.amazonaws.com
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          output-env-credentials: true

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Free disk space
        run: |
          docker system prune -af --volumes
          df -h

      - name: Debug build context
        run: ls -R services/triton

      - name: Build Triton Image
        run: |
          ECR="${{ secrets.AWS_ECR_URI }}"
          SHA=$(git rev-parse --short HEAD)

          docker build -t triton:latest \
           -f services/triton/Dockerfile \
           services/triton

          docker tag triton:latest $ECR:latest
          docker tag triton:latest $ECR:$SHA

      - name: Push Images
        run: |
          ECR="${{ secrets.AWS_ECR_URI }}"
          SHA=$(git rev-parse --short HEAD)

          docker push $ECR:latest
          docker push $ECR:$SHA

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME
          kubectl config view
          kubectl get nodes

      - name: Deploy Triton Pod
        run: |
          kubectl apply -f k8s/triton-deployment.yaml --validate=false
