---
name: Build & Push Triton Image

on:
  push:
    branches: ["main"]
    paths:
      - "services/triton/**"

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # -------------------------------
      # AWS Credentials
      # -------------------------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Free disk space
        run: |
          docker system prune -af --volumes
          df -h

      - name: Debug build context
        run: ls -R services/triton

      # -------------------------------
      # Docker Build + Push
      # -------------------------------
      - name: Build Triton image
        run: |
          ECR="${{ secrets.AWS_ECR_URI }}"
          SHA=$(git rev-parse --short HEAD)

          docker build \
            -t triton:latest \
            -f services/triton/Dockerfile \
            services/triton

          docker tag triton:latest $ECR:latest
          docker tag triton:latest $ECR:$SHA

      - name: Push image to ECR
        run: |
          ECR="${{ secrets.AWS_ECR_URI }}"
          SHA=$(git rev-parse --short HEAD)

          docker push $ECR:latest
          docker push $ECR:$SHA
