---
name: Build & Push Triton Image

"on":
  push:
    branches: ["main"]
    paths:
      - "services/triton/**"

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: us-east-1

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Image
        run: |
          ECR="${{ secrets.AWS_ECR_URI }}"
          SHA=$(git rev-parse --short HEAD)

          docker build -t triton:latest services/triton

          docker tag triton:latest $ECR:latest
          docker tag triton:latest $ECR:$SHA

      - name: Push Images
        run: |
          ECR="${{ secrets.AWS_ECR_URI }}"
          SHA=$(git rev-parse --short HEAD)
          docker push $ECR:latest
          docker push $ECR:$SHA
